package com.rideshare.model;
// Generated Aug 28, 2016 5:05:00 PM by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Posts generated by hbm2java
 */
@Entity
@Table(name = "posts", catalog = "sql9133240")
public class Posts implements java.io.Serializable {

	private Integer postid;
	private int userid;
	private String post;
	private int posttype;
	private Date datecreated;
	private Date dateupdated;

	public Posts() {
	}

	public Posts(int userid, String post, int posttype, Date datecreated, Date dateupdated) {
		this.userid = userid;
		this.post = post;
		this.posttype = posttype;
		this.datecreated = datecreated;
		this.dateupdated = dateupdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "postid", unique = true, nullable = false)
	public Integer getPostid() {
		return this.postid;
	}

	public void setPostid(Integer postid) {
		this.postid = postid;
	}

	@Column(name = "userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "post", nullable = false, length = 65535)
	public String getPost() {
		return this.post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	@Column(name = "posttype", nullable = false)
	public int getPosttype() {
		return this.posttype;
	}

	public void setPosttype(int posttype) {
		this.posttype = posttype;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datecreated", nullable = false, length = 19)
	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateupdated", nullable = false, length = 19)
	public Date getDateupdated() {
		return this.dateupdated;
	}

	public void setDateupdated(Date dateupdated) {
		this.dateupdated = dateupdated;
	}

	@Override
	public String toString() {
		return "Posts [postid=" + postid + ", userid=" + userid + ", post=" + post + ", posttype=" + posttype
				+ ", datecreated=" + datecreated + ", dateupdated=" + dateupdated + "]";
	}

}
